version: "3"
services:
  app:
    container_name: monetary-evolution
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
    command:
      [
        "./scripts/wait-for-it.sh",
        "${DB_HOST}:${DB_PORT}",
        "-t",
        "15",
        "--",
        "./scripts/start-for-local-development.sh",
      ]
    networks:
      - monetary-evolution-net
  db:
    container_name: monetary-evolution-db
    image: postgres:15-alpine
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file: .env
    networks:
      - monetary-evolution-net
networks:
  monetary-evolution-net:
    driver: bridge
