# -*- coding: utf-8 -*-
# Generated by Django 4.2.4 on 2023-09-03 00:47

import uuid

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monetary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data da última atualização"
                    ),
                ),
                ("name", models.CharField(max_length=5)),
                ("value", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "variation_date",
                    models.DateTimeField(verbose_name="Data da variação"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monetary",
            constraint=models.UniqueConstraint(
                fields=("name", "variation_date"), name="unique_name_variation_date"
            ),
        ),
    ]
